import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { convertGeminiAudioToWavBase64 } from '@/utils/audioConversion';

export async function POST(req: NextRequest) {
  try {
    const { text, voice = 'Kore' } = await req.json();

    if (!text || typeof text !== 'string' || !text.trim()) {
      return NextResponse.json({ error: 'Text prompt is required for TTS' }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: 'GEMINI_API_KEY not configured' }, { status: 500 });
    }

    const ai = new GoogleGenAI({ apiKey });
    const ttsRes = await ai.models.generateContent({
      model: 'gemini-2.5-flash-preview-tts',
      contents: [{ role: 'user', parts: [{ text: text.trim() }] }],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voice || 'Kore',
            },
          },
        },
      },
    });

    const part = ttsRes.candidates?.[0]?.content?.parts?.[0];
    const rawAudio = part?.inlineData?.data;
    const rawMime = part?.inlineData?.mimeType || 'audio/pcm';

    if (!rawAudio) {
      return NextResponse.json({ error: 'No audio generated by Gemini TTS' }, { status: 502 });
    }

    const converted = convertGeminiAudioToWavBase64(rawAudio, rawMime);

    return NextResponse.json({
      success: true,
      audioBase64: converted.audioBase64,
      mimeType: converted.mimeType || 'audio/wav',
    });
  } catch (error: any) {
    console.error('Gemini TTS error:', error);
    return NextResponse.json(
      { error: error?.message || 'Failed to synthesize speech' },
      { status: 500 }
    );
  }
}
